language: node_js

sudo: false

node_js:
  - "node"
  - "12"
  - "10"


install:
  - npm install

script:
  - npm test

# whitelist
branches:
  only:
    - master

after_success:
  - npm run report-coverage
