language: node_js

sudo: false

node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"


install:
  - npm install

script:
  - npm test

# whitelist
branches:
  only:
    - master
    - /^greenkeeper/.*$/

after_success:
  - npm run report-coverage
