language: node_js

sudo: false

node_js:
  - "node"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"


install:
  - npm install

script:
  - npm test

# whitelist
branches:
  only:
    - master
    - /^greenkeeper/.*$/
